webtalk_init -webtalk_dir F:/FYP-FINAL/integration_try2/integration_try1.sim/sim_1/behav/xsim/xsim.dir/Integrator_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 30 22:19:19 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "563d0063-4d37-42fc-a693-a99c2f52cf7b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1a5e0d0325ac4d40b473a3f339e17514" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "79" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "288589900 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "498.95_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "31176_KB" -context "xsim\\usage"
webtalk_transmit -clientid 207501291 -regid "" -xml F:/FYP-FINAL/integration_try2/integration_try1.sim/sim_1/behav/xsim/xsim.dir/Integrator_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/FYP-FINAL/integration_try2/integration_try1.sim/sim_1/behav/xsim/xsim.dir/Integrator_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/FYP-FINAL/integration_try2/integration_try1.sim/sim_1/behav/xsim/xsim.dir/Integrator_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
