webtalk_init -webtalk_dir C:/Users/sujan/Desktop/project final files/Vivado_write_read-20200504T155658Z-001/Vivado_write_read/Vivado_write_read.sim/sim_1/behav/xsim/xsim.dir/Integrator_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May  5 14:35:17 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211702663_0_0_304" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f6f982b1-5b3b-4b74-80c0-50b92f6c212c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "110dbef765344c189bedf8564b105026" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "54" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.51_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "31908_KB" -context "xsim\\usage"
webtalk_transmit -clientid 269790905 -regid "211702663_0_0_304" -xml C:/Users/sujan/Desktop/project final files/Vivado_write_read-20200504T155658Z-001/Vivado_write_read/Vivado_write_read.sim/sim_1/behav/xsim/xsim.dir/Integrator_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/sujan/Desktop/project final files/Vivado_write_read-20200504T155658Z-001/Vivado_write_read/Vivado_write_read.sim/sim_1/behav/xsim/xsim.dir/Integrator_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/sujan/Desktop/project final files/Vivado_write_read-20200504T155658Z-001/Vivado_write_read/Vivado_write_read.sim/sim_1/behav/xsim/xsim.dir/Integrator_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
