# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FYP-FINAL/final project/final project.srcs/sources_1/ip/cordic_3/cordic_3.xci
# IP: The module: 'cordic_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FYP-FINAL/final project/final project.srcs/sources_1/ip/cordic_3/cordic_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/FYP-FINAL/final project/final project.srcs/sources_1/ip/cordic_3/cordic_3.xci
# IP: The module: 'cordic_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FYP-FINAL/final project/final project.srcs/sources_1/ip/cordic_3/cordic_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
