# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/AMRITHA/integration_try1/integration_try1.srcs/sources_1/ip/cordic_1/cordic_1.xci
# IP: The module: 'cordic_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AMRITHA/integration_try1/integration_try1.srcs/sources_1/ip/cordic_1/cordic_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/AMRITHA/integration_try1/integration_try1.srcs/sources_1/ip/cordic_1/cordic_1.xci
# IP: The module: 'cordic_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AMRITHA/integration_try1/integration_try1.srcs/sources_1/ip/cordic_1/cordic_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
