# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Repository/FYP-FINAL/project final files/project_1/project_1.runs/cordic_1_synth_1/.Xil/Vivado-11276-DESKTOP-I2LGHSG/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k70tfbv676-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xbip_utils_v3_0_9 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/xbip_utils_v3_0_vh_rfs.vhd}}
      rt::read_vhdl -lib c_reg_fd_v12_0_5 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/c_reg_fd_v12_0_vh_rfs.vhd}}
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_4 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd}}
      rt::read_vhdl -lib xbip_pipe_v3_0_5 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/xbip_pipe_v3_0_vh_rfs.vhd}}
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_5 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd}}
      rt::read_vhdl -lib xbip_addsub_v3_0_5 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/xbip_addsub_v3_0_vh_rfs.vhd}}
      rt::read_vhdl -lib c_addsub_v12_0_12 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/c_addsub_v12_0_vh_rfs.vhd}}
      rt::read_vhdl -lib xbip_bram18k_v3_0_5 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/xbip_bram18k_v3_0_vh_rfs.vhd}}
      rt::read_vhdl -lib mult_gen_v12_0_14 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/mult_gen_v12_0_vh_rfs.vhd}}
      rt::read_vhdl -lib axi_utils_v2_0_5 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/axi_utils_v2_0_vh_rfs.vhd}}
      rt::read_vhdl -lib cordic_v6_0_14 {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/hdl/cordic_v6_0_vh_rfs.vhd}}
      rt::read_vhdl -lib xil_defaultlib {{d:/Repository/FYP-FINAL/project final files/project_1/project_1.srcs/sources_1/ip/cordic_1/synth/cordic_1.vhd}}
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList {{D:/Repository/FYP-FINAL/project final files/project_1/project_1.runs/cordic_1_synth_1/.Xil/Vivado-11276-DESKTOP-I2LGHSG/realtime/cordic_1_synth.xdc}}
    rt::sdcChecksum
    set rt::top cordic_1
    rt::set_parameter enableIncremental true
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/Repository/FYP-FINAL/project final files/project_1/project_1.runs/cordic_1_synth_1/.Xil/Vivado-11276-DESKTOP-I2LGHSG/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
